config/routes.rb
Boxroom::Application.routes.draw do
  get '/signin', :to => 'sessions#new'
  delete '/signout', :to => 'sessions#destroy'

  # Resources
  resources :admins, :only => [:new, :create]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :reset_password, :except => [:index, :show, :destroy]
  resources :users, :except => :show
  resources :groups, :except => :show
  resources :files, :except => [:index, :new, :create]
  resources :share_links, :only => [:index, :show, :destroy]
  resources :versions, :only => [:index]
  resources :clipboard, :only => [:create, :destroy] do
    post 'copy', :on => :member
    post 'move', :on => :member
    put 'reset', :on => :member
  end

  # Update a collection of permissions
  resources :permissions, :only => :update_multiple do
    put :update_multiple, :on => :collection
  end

  # Nested resources
  resources :folders, :shallow => true, :except => [:new, :create] do
    resources :folders, :only => [:new, :create]
    resources :files, :only => [:new, :create]
  end

  resources :files, :shallow => :true, :only => :show do
    resources :share_links, :only => [:new, :create]
  end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  match "/versions/:id" => "version#index"
  root :to => "folders#index"
end

app/models/folder.rb
class Folder < ActiveRecord::Base
  acts_as_tree :order => 'name'

  has_many :user_files, :dependent => :destroy, :order => 'attachment_file_name'
  has_many :permissions, :dependent => :destroy

  attr_accessor :is_copied_folder
  attr_accessible :name, :user_id

  validates_uniqueness_of :name, :scope => :parent_id
  validates_presence_of :name

  before_save :check_for_parent
  after_create :create_permissions, :unless => :is_copied_folder
  before_destroy :dont_destroy_root_folder

  def copy(target_folder, originally_copied_folder = nil)
    new_folder = self.clone
    new_folder.is_copied_folder = true
    new_folder.parent = target_folder
    new_folder.save!

    originally_copied_folder = new_folder if originally_copied_folder.nil?

    # Copy original folder's permissions
    self.permissions.each do |permission|
      new_permission = permission.clone
      new_permission.folder = new_folder
      new_permission.save!
    end

    self.user_files.each do |file|
      file.copy(new_folder)
    end

    # Copy sub-folders recursively
    self.children.each do |folder|
      folder.copy(new_folder, originally_copied_folder) unless folder == originally_copied_folder
    end

    new_folder
  end

  def move(target_folder)
    unless target_folder == self || self.parent_of?(target_folder)
      self.parent = target_folder
      save!
    else
      raise 'You cannot move a folder to its own sub-folder.'
    end
  end

  def parent_of?(folder)
    self.children.each do |child|
      if child == folder
        return true
      else
        return child.parent_of?(folder)
      end
    end
    false
  end

  def is_root?
    parent.nil? && !new_record?
  end

  def has_children?
    children.count > 0
  end

  def self.root
    find_by_name_and_parent_id('Root folder', nil)
  end

  private

  def check_for_parent
    raise 'Folders must have a parent.' if parent.nil? && name != 'Root folder'
  end

  def create_permissions
    unless is_root?
      parent.permissions.each do |permission|
        Permission.create! do |p|
          p.group = permission.group
          p.folder = self
          p.can_create = permission.can_create
          p.can_read = permission.can_read
          p.can_update = permission.can_update
          p.can_delete = permission.can_delete
        end
      end
    end
  end

  def dont_destroy_root_folder
    raise "Can't delete Root folder" if is_root?
  end
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  before_filter :require_existing_folder, :only => [:show, :edit, :update, :destroy]
  before_filter :require_existing_target_folder, :only => [:new, :create]
  before_filter :require_folder_isnt_root_folder, :only => [:edit, :update, :destroy]

  before_filter :require_create_permission, :only => [:new, :create]
  before_filter :require_read_permission, :only => :show
  before_filter :require_update_permission, :only => [:edit, :update]
  before_filter :require_delete_permission, :only => :destroy

  def index
    redirect_to folder_url(Folder.root)
  end

  # Note: @folder is set in require_existing_folder
  def show
    @files_shown = Array.new
  end

  # Note: @target_folder is set in require_existing_target_folder
  def new
    @folder = @target_folder.children.build
  end

  # Note: @target_folder is set in require_existing_target_folder
  def create
    @folder = @target_folder.children.build(params[:folder])

    if @folder.save
      redirect_to folder_url(@target_folder)
    else
      render :action => 'new'
    end
  end

  # Note: @folder is set in require_existing_folder
  def edit
  end

  # Note: @folder is set in require_existing_folder
  def update
    if @folder.update_attributes(params[:folder])
      redirect_to edit_folder_url(@folder), :notice => t(:your_changes_were_saved)
    else
      render :action => 'edit'
    end
  end

  # Note: @folder is set in require_existing_folder
  def destroy
    target_folder = @folder.parent
    @folder.destroy
    redirect_to folder_url(target_folder)
  end

  private

  def require_existing_folder
    @folder = Folder.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to folder_url(Folder.root), :alert => t(:already_deleted, :type => t(:this_folder))
  end

  def require_folder_isnt_root_folder
    if @folder.is_root?
      redirect_to folder_url(Folder.root), :alert => t(:cannot_delete_root_folder)
    end
  end

  # Overrides require_delete_permission in ApplicationController
  def require_delete_permission
    unless @folder.is_root? || current_user.can_delete(@folder)
      redirect_to folder_url(@folder.parent), :alert => t(:no_permissions_for_this_type, :method => t(:delete), :type =>t(:this_folder))
    else
      require_delete_permissions_for(@folder.children)
    end
  end

  def require_delete_permissions_for(folders)
    folders.each do |folder|
      unless current_user.can_delete(folder)
        redirect_to folder_url(@folder.parent), :alert => t(:no_delete_permissions_for_subfolder)
      else
        # Recursive...
        require_delete_permissions_for(folder.children)
      end
    end
  end
end

app/helpers/folders_helper.rb
module FoldersHelper
  def breadcrumbs(folder, breadcrumbs = '')
    breadcrumbs = "<span class=\"breadcrumb nowrap\">#{link_to(folder.parent.name, folder.parent)}</span> &raquo; #{breadcrumbs}"
    breadcrumbs = breadcrumbs(folder.parent, breadcrumbs) unless folder.parent == Folder.root
    breadcrumbs.html_safe
  end

  def file_icon(extension)
    if FileTest.exists?("#{Rails.root}/public/images/fileicons/#{extension}.png")
      "fileicons/#{extension}.png"
    else
      'file.png'
    end
  end
end

app/views/folders/_form.html.erb
<%= f.error_messages %>
<p>
	<%= f.label :name %>:<br>
	<%= f.text_field :name, { :class => 'text_input' } %>
</p>
<p>
	<%= f.submit t(:save) %> &nbsp; &mdash; &nbsp;
	<%= link_to t(:back), folder_url(@folder.parent) %>
</p>

app/views/folders/edit.html.erb
<% content_for :title, t(:rename_folder) -%>

<h1><%= content_for :title %></h1>
<% if flash[:notice] -%>
<p class="notice" id="notice">
	<%= flash[:notice] %>
</p>
<% end -%>
<%= form_for @folder do |f| %>
	<%= render :partial => 'form', :locals => { :f => f } %>
<% end %>

app/views/folders/new.html.erb
<% content_for :title, t(:new_folder) -%>

<h1><%= content_for :title %></h1>
<%= form_for [@target_folder, @folder] do |f| %>
	<%= render :partial => 'form', :locals => { :f => f } %>
<% end %>

app/views/folders/show.html.erb
<% content_for :title, @folder.name -%>

<h1><%= content_for :title %></h1>
<% unless @folder.is_root? -%>
<p>
  <%= breadcrumbs(@folder) %>
  <span class="breadcrumb nowrap"><%= @folder.name %></span>
</p>
<% end -%>
<% if flash[:notice] -%>
<p class="notice" id="notice">
  <%= flash[:notice] %>
</p>
<% end -%>
<% if flash[:alert] -%>
<p class="error" id="alert">
  <%= flash[:alert] %>
</p>
<% end -%><p>
<% if current_user.can_create(@folder) -%>
  <span class="folder_menu"><%= image_tag('folder_add.png', :alt => t(:create_a_new_folder)) %> <%= link_to t(:create_a_new_folder), new_folder_folder_path(@folder) %></span>
  <span class="folder_menu"><%= image_tag('file_add.png', :alt => t(:upload_a_file)) %> <%= link_to t(:upload_a_file), new_folder_file_path(@folder) %></span>
<% end -%>
<% if current_user.member_of_admins? -%>
  <span class="folder_menu" id="show_permissions_link"><span><%= image_tag('permissions.png', :alt => t(:permissions)) %> <%= link_to_function t(:permissions), "show_element('permissions')" %></span></span>
<% end -%>
  <span class="folder_menu" id="show_clipboard_link"><span><%= image_tag('clipboard.png', :alt => t(:clipboard)) %> <%= link_to_function t(:clipboard), "show_element('clipboard')" %></span></span>
</p>
<div id="files_and_folders">
  <table>
    <tr>
      <th></th>
      <th><%= t :name %></th>
      <th><%= t :size %></th>
      <th><%= t :date_modified %></th>
      <th></th>
    </tr>
  <% unless @folder.is_root? -%>
    <tr class="<%= cycle('even','odd') %>">
      <td><%= image_tag('folder.png') %></td>
      <td class="file_name">&uarr; <%= link_to t(:up), folder_path(@folder.parent), :title => @folder.parent.name %></td>
      <td class="file_size">--</td>
      <td class="file_modified">--</td>
      <td></td>
    </tr>
  <% end -%>
  <% @folder.children.each do |folder| -%>
    <% if current_user.can_read(folder) -%>
    <tr class="<%= cycle('even','odd') %>">
      <td><%= image_tag('folder.png') %></td>
      <td class="file_name"><%= link_to folder.name, folder_path(folder) %></td>
      <td class="file_size">--</td>
      <td class="file_modified"><%= l folder.updated_at, :format => :long %></td>
      <td>
      <% if current_user.can_update(folder) -%>
        <%= link_to image_tag('edit.png', :alt => t(:edit)), edit_folder_path(folder), :title => t(:edit) %>&nbsp;
      <% end -%>
      <% if current_user.can_delete(folder) -%>
        <%= link_to image_tag('delete.png', :alt => t(:delete_item)), folder_path(folder), :method => :delete, :confirm => t(:are_you_sure), :title => t(:delete_item) %>&nbsp;
      <% end -%>
        <%= link_to image_tag('clipboard_add.png', :alt => t(:add_to_clipboard)),
          { :controller => :clipboard, :action => :create, :id => folder.id, :type => 'folder', :folder_id => @folder, :authenticity_token => form_authenticity_token },
          :method => :post, :title => t(:add_to_clipboard)
        %>
      </td>
    </tr>
    <% end -%>
  <% end -%>
  <% @folder.user_files.sort! { |a,b| a.id <=> b.id } -%>
  <% puts @folder.user_files.all %>
  <% @folder.user_files.each do |file| -%>
        <% if current_user.can_read(@folder) -%>
      <% unless @files_shown.include?(file.attachment_file_name) -%>
    <tr class="<%= cycle('even','odd') %>">
      <td><%= image_tag(file_icon(file.extension)) %></td>
      <td class="file_name"><%= link_to file.attachment_file_name, file_path(file), :title => "#{t(:download)} #{file.attachment_file_name}" %></td>
      <td class="file_size"><%= number_to_human_size(file.attachment_file_size, :locale=>I18n.locale) %></td>
      <td class="file_modified"><%= l file.updated_at, :format => :long %></td>
      <td>
      <% if current_user.can_update(file.folder) -%>
        <%= link_to image_tag('edit.png', :alt => t(:edit)), edit_file_path(file), :title => t(:edit) %>&nbsp;
      <% end -%>
      <% if current_user.can_delete(file.folder) -%>
        <%= link_to image_tag('delete.png', :alt => t(:delete_item)), file_path(file), :method => :delete, :confirm => t(:are_you_sure), :title => t(:delete_item) %>&nbsp;
      <% end -%>
        <%= link_to image_tag('clipboard_add.png', :alt => t(:add_to_clipboard)),
          { :controller => :clipboard, :action => :create, :id => file.id, :type => 'file', :folder_id => @folder, :authenticity_token => form_authenticity_token },
          :method => :post, :title => t(:add_to_clipboard)
          %>&nbsp; <%= link_to 'Version', {:controller => :version, :method => :index, :id => file.id} %>
        <%= link_to image_tag('share.png', :alt => t(:share)), new_file_share_link_path(file), :title => t(:share) %>
      </td>
    </tr>
  <% end %>
  <%
      @files_shown << file.attachment_file_name unless @files_shown.include?(file.attachment_file_name)
      puts @files_shown
    %>

  <% end-%>
  <% end -%>
  </table>
</div>
<% if current_user.member_of_admins? -%>
<div id="permissions" style="display:none;">
  <%= render 'permissions/form' %>
</div>
<% end -%>
<div id="clipboard" style="display:none;">
  <%= render 'clipboard/show' %>
</div>