config/routes.rb
Boxroom::Application.routes.draw do
  get '/signin', :to => 'sessions#new'
  delete '/signout', :to => 'sessions#destroy'

  # Resources
  resources :admins, :only => [:new, :create]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :reset_password, :except => [:index, :show, :destroy]
  resources :users, :except => :show
  resources :groups, :except => :show
  resources :files, :except => [:index, :new, :create]
  resources :share_links, :only => [:index, :show, :destroy]
  resources :versions, :only => [:index]
  resources :clipboard, :only => [:create, :destroy] do
    post 'copy', :on => :member
    post 'move', :on => :member
    put 'reset', :on => :member
  end

  # Update a collection of permissions
  resources :permissions, :only => :update_multiple do
    put :update_multiple, :on => :collection
  end

  # Nested resources
  resources :folders, :shallow => true, :except => [:new, :create] do
    resources :folders, :only => [:new, :create]
    resources :files, :only => [:new, :create]
  end

  resources :files, :shallow => :true, :only => :show do
    resources :share_links, :only => [:new, :create]
  end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  match "/versions/:id" => "version#index"
  root :to => "folders#index"
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :permissions, :dependent => :destroy
  has_and_belongs_to_many :users

  validates_uniqueness_of :name
  validates_presence_of :name

  after_create :create_admin_permissions, :if => :admins_group?
  after_create :create_permissions, :unless => :admins_group?
  before_destroy :dont_destroy_admins

  def admins_group?
    name == 'Admins'
  end

  private

  def create_admin_permissions
    Folder.all.each do |folder|
      Permission.create! do |p|
        p.group = self
        p.folder = folder
        p.can_create = true
        p.can_read = true
        p.can_update = true
        p.can_delete = true
      end
    end
  end

  def create_permissions
    Folder.all.each do |folder|
      Permission.create! do |p|
        p.group = self
        p.folder = folder
        p.can_create = false
        p.can_read = folder.is_root? # New groups can read the root folder
        p.can_update = false
        p.can_delete = false
      end
    end
  end

  def dont_destroy_admins
    raise "Can't delete admins group" if admins_group?
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :require_admin
  before_filter :require_existing_group, :only => [:edit, :update, :destroy]
  before_filter :require_group_isnt_admins_group, :only => [:edit, :update, :destroy]

  def index
    @groups = Group.all(:order => 'name')
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(params[:group])

    if @group.save
      redirect_to groups_url
    else
      render :action => 'new'
    end
  end

  # Note: @group is set in require_existing_group
  def edit
  end

  # Note: @group is set in require_existing_group
  def update
    if @group.update_attributes(params[:group])
      redirect_to edit_group_url(@group), :notice => t(:your_changes_were_saved)
    else
      render :action => 'edit'
    end
  end

  # Note: @group is set in require_existing_group
  def destroy
    @group.destroy
    redirect_to groups_url
  end

  private

  def require_existing_group
    @group = Group.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to groups_url, :alert => t(:group_already_deleted)
  end

  def require_group_isnt_admins_group
    if @group.admins_group?
      redirect_to groups_url, :alert => t(:admins_group_cannot_be_deleted)
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for @group do |f| %>
	<%= f.error_messages %>
	<p>
		<%= f.label :name %>:<br>
		<%= f.text_field :name, { :class => 'text_input' } %>
	</p>
	<p>
		<%= f.submit t(:save) %> &nbsp; &mdash; &nbsp;
		<%= link_to t(:back), groups_url %>
	</p>
<% end %>

app/views/groups/edit.html.erb
<% content_for :title, t(:rename_group) -%>

<h1><%= content_for :title %></h1>
<% if flash[:notice] -%>
<p class="notice" id="notice">
	<%= flash[:notice] %>
</p>
<% end -%>
<%= render 'form' %>

app/views/groups/index.html.erb
<% content_for :title, t(:groups) -%>

<h1><%= content_for :title %></h1>
<% if flash[:alert] -%>
<p class="error" id="alert">
	<%= flash[:alert] %>
</p>
<% end -%>
<p>
	<span class="group_menu"><%= image_tag('group_add.png', :alt => t(:create_a_new_group)) %> <%= link_to t(:create_a_new_group), new_group_path %></span>
</p>
<table>
	<tr>
		<th></th>
		<th><%t :name %></th>
		<th></th>
	</tr>
<% @groups.each do |group| -%>
	<tr class="<%= cycle('even','odd') %>">
	<% if group.admins_group? -%>
		<td><%= image_tag('group_grey.png') %></td>
		<td class="group_name disabled"><%= group.name %></td>
		<td></td>
	<% else -%>
		<td><%= image_tag('group.png') %></td>
		<td class="group_name"><%= group.name %></td>
		<td>
			<%= link_to image_tag('edit.png', :alt => t(:edit)), edit_group_path(group), :title => t(:edit) %>&nbsp;
			<%= link_to image_tag('delete.png', :alt => t(:delete_item)), group_path(group), :method => :delete, :confirm => t(:are_you_sure), :title => t(:delete_item) %>
		</td>
	<% end -%>
	</tr>
<% end -%>
</table>

app/views/groups/new.html.erb
<% content_for :title, t(:new_group) -%>

<h1><%= content_for :title %></h1>
<%= render 'form' %>