config/routes.rb
Boxroom::Application.routes.draw do
  get '/signin', :to => 'sessions#new'
  delete '/signout', :to => 'sessions#destroy'

  # Resources
  resources :admins, :only => [:new, :create]
  resources :sessions, :only => [:new, :create, :destroy]
  resources :reset_password, :except => [:index, :show, :destroy]
  resources :users, :except => :show
  resources :groups, :except => :show
  resources :files, :except => [:index, :new, :create]
  resources :share_links, :only => [:index, :show, :destroy]
  resources :versions, :only => [:index]
  resources :clipboard, :only => [:create, :destroy] do
    post 'copy', :on => :member
    post 'move', :on => :member
    put 'reset', :on => :member
  end

  # Update a collection of permissions
  resources :permissions, :only => :update_multiple do
    put :update_multiple, :on => :collection
  end

  # Nested resources
  resources :folders, :shallow => true, :except => [:new, :create] do
    resources :folders, :only => [:new, :create]
    resources :files, :only => [:new, :create]
  end

  resources :files, :shallow => :true, :only => :show do
    resources :share_links, :only => [:new, :create]
  end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  match "/versions/:id" => "version#index"
  root :to => "folders#index"
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :groups

  attr_accessor :password_confirmation, :password_required, :dont_clear_reset_password_token
  attr_accessible :name, :email, :password, :password_confirmation, :password_required

  validates_confirmation_of :password
  validates_length_of :password, :in => 6..20, :allow_blank => true
  validates_presence_of :password, :if => :password_required
  validates_presence_of :name, :email
  validates_uniqueness_of :name, :email
  validates_format_of :email, :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/

  before_save :clear_reset_password_token, :unless => :dont_clear_reset_password_token
  after_create :create_root_folder_and_admins_group, :if => :is_admin
  before_destroy :dont_destroy_admin

  %w{create read update delete}.each do |method|
    define_method "can_#{method}" do |folder|
      has_permission = false
      groups.each do |group|
        unless group.permissions.send("find_by_folder_id_and_can_#{method}", folder.id, true).blank?
          has_permission = true
          break
        end
      end
      has_permission
    end
  end

  def password
    @password
  end

  def password=(new_password)
    @password = new_password
    unless @password.blank?
      self.password_salt = SecureRandom.base64(32)
      self.hashed_password = Digest::SHA256.hexdigest(password_salt + password)
    end
  end

  def member_of_admins?
    !groups.find_by_name('Admins').blank?
  end

  def refresh_reset_password_token
    self.reset_password_token = SecureRandom.hex(10)
    self.reset_password_token_expires_at = 1.hour.from_now
    self.dont_clear_reset_password_token = true
    save(:validate => false)
  end

  def refresh_remember_token
    self.remember_token = SecureRandom.base64(32)
    save(:validate => false)
  end

  def forget_me
    self.remember_token = nil
    save(:validate => false)
  end

  def self.authenticate(name, password)
    return nil if name.blank? || password.blank?
    user = find_by_name(name) or return nil
    hash = Digest::SHA256.hexdigest(user.password_salt + password)
    hash == user.hashed_password ? user : nil
  end

  def self.no_admin_yet?
    find_by_is_admin(true).blank?
  end

  private

  def clear_reset_password_token
    self.reset_password_token = nil
    self.reset_password_token_expires_at = nil
  end

  def create_root_folder_and_admins_group
    Folder.create(:name => 'Root folder')
    groups << Group.create(:name => 'Admins')
  end

  def dont_destroy_admin
    raise "Can't delete original admin user" if is_admin
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_admin, :except => [:edit, :update]
  before_filter :require_existing_user, :only => [:edit, :update, :destroy]
  before_filter :require_deleted_user_isnt_admin, :only => :destroy

  def index
    @users = User.all(:order => 'name')
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user].merge({ :password_required => true }))

    if @user.save
      set_groups
      redirect_to users_url
    else
      render :action => 'new'
    end
  end

  # Note: @user is set in require_existing_user
  def edit
  end

  # Note: @user is set in require_existing_user
  def update
    if @user.update_attributes(params[:user].merge({ :password_required => false }))
      set_groups
      redirect_to edit_user_url(@user), :notice => t(:your_changes_were_saved)
    else
      render :action => 'edit'
    end
  end

  # Note: @user is set in require_existing_user
  def destroy
    @user.destroy
    redirect_to users_url
  end

  private

  def require_existing_user
    if current_user.member_of_admins? && params[:id] != current_user.id.to_s
      @title = t(:edit_user)
      @user = User.find(params[:id])
    else
      @title = t(:account_settings)
      @user = current_user
    end
  rescue ActiveRecord::RecordNotFound
    redirect_to users_url, :alert => t(:user_already_deleted)
  end

  def require_deleted_user_isnt_admin
    if @user.is_admin
      redirect_to users_url, :alert => t(:admin_user_cannot_be_deleted)
    end
  end

  def set_groups
    if current_user.member_of_admins?
      @user.group_ids = params[:user][:group_ids]
      @user.groups << Group.find_by_name('Admins') if @user.is_admin
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_belongs_to_group(group)
    unless @user.nil?
      @user.groups.include?(group)
    end
  end
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
	<%= f.error_messages %>
	<p>
		<%= f.label :name %>:<br>
		<%= f.text_field :name, { :class => 'text_input' } %>
	</p>
	<p>
		<%= f.label :email %>:<br>
		<%= f.text_field :email, { :class => 'text_input' } %>
	</p>
	<p>
		<%= f.label :password %>:<br>
		<%= f.password_field :password, { :class => 'text_input' } %>
	</p>
	<p>
		<%= label_tag t(:confirm_password) %>:<br>
		<%= f.password_field :password_confirmation, { :class => 'text_input' } %>
	</p>
	<% if current_user.member_of_admins? -%>
	<p>
		<%= t :member_of_these_groups %>:
		<span class="user_groups">
		<% Group.all.each do |group| -%>
		<% if @user.is_admin && group.admins_group? -%>
			<span class="group nowrap disabled">
				<input type="checkbox" checked="checked" disabled="disabled" />
				<%= group.name %>
			</span>
		<% else -%>
			<span class="group nowrap">
				<%= check_box_tag('user[group_ids][]', group.id, user_belongs_to_group(group)) %>
				<%= group.name %>
			</span>
		<% end -%>
		<% end -%>
		</span>
	</p>
	<% end -%>
	<p>
		<%= f.submit t(:save) %>
	<% if @user != current_user -%>
		&nbsp; &mdash; &nbsp;
		<%= link_to t(:back), users_url %>
	<% end -%>
	</p>
<% end %>

app/views/users/edit.html.erb
<% content_for :title, @title -%>

<h1><%= content_for :title %></h1>
<% if flash[:notice] -%>
<p class="notice" id="notice">
	<%= flash[:notice] %>
</p>
<% end -%>
<%= render 'form' %>

app/views/users/index.html.erb
<% content_for :title, t(:users) -%>

<h1><%= content_for :title %></h1>
<% if flash[:alert] -%>
<p class="error" id="alert">
	<%= flash[:alert] %>
</p>
<% end -%>
<p>
	<span class="user_menu"><%= image_tag('user_add.png', :alt => t(:create_a_new_user)) %> <%= link_to t(:create_a_new_user), new_user_path %></span>
</p>
<table>
	<tr>
		<th></th>
		<th><%= t :name %></th>
		<th><%= t :email %></th>
		<th></th>
	</tr>
<% @users.each do |user| -%>
	<tr class="<%= cycle('even','odd') %>">
		<td><%= image_tag('user.png') %></td>
		<td class="user_name"><%= user.name %></td>
		<td class="user_email"><%= user.email %></td>
		<td>
			<%= link_to image_tag('edit.png', :alt => t(:edit)), edit_user_path(user), :title => t(:edit) %>&nbsp;
		<% unless user.is_admin -%>
			<%= link_to image_tag('delete.png', :alt => t(:delete_item)), user_path(user), :method => :delete, :confirm => t(:are_you_sure), :title => t(:delete_item) %>
		<% end -%>
		</td>
	</tr>
<% end -%>
</table>

app/views/users/new.html.erb
<% content_for :title, t(:new_user) -%>

<h1><%= content_for :title %></h1>
<%= render 'form' %>